### ISSUE TITLE
[question] Got 'relation "plenario_user" does not exist' Error during login

### ISSUE THREAD

**Issue by my-zhang** [UrbanCCD-UChicago/plenario#173]
I've setup everything as README says, however it seems that during the login it tries to query a table called "**plenario_user**", which seems to be not existed. The error states `relation "plenario_user" does not exist`. 

And I checked the table list inside the db "plenario_dev" using `\db *`, however there're only system tables(pg_*).  Thus I was wondering whether the program failed to create the table, or it only create that table when new user is created. If the later case, how can I login using the account written in `settings.py` without querying the table "plenario_user"?

Here's the complete trace

```
mzhang@ubuntu:~/workspace/projects/plenario$ python runserver.py 
Raven is not configured (logging is disabled). Please see the documentation for more information.
 * Running on http://127.0.0.1:5001/ (Press CTRL+C to quit)
 * Restarting with stat
Raven is not configured (logging is disabled). Please see the documentation for more information.
2015-02-01 17:59:33 PST ERROR:  relation "plenario_user" does not exist at character 187
2015-02-01 17:59:33 PST STATEMENT:  SELECT plenario_user.password AS plenario_user_password, plenario_user.id AS plenario_user_id, plenario_user.name AS plenario_user_name, plenario_user.email AS plenario_user_email 
	FROM plenario_user 
	WHERE plenario_user.email = 'mengyuzhang@uchicago.edu' 
	 LIMIT 1
127.0.0.1 - - [01/Feb/2015 17:59:34] "POST /login/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/raven/middleware.py", line 35, in __call__
    iterable = self.application(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mzhang/workspace/projects/plenario/plenario/auth.py", line 118, in login
    if form.validate_on_submit():
  File "/usr/local/lib/python2.7/dist-packages/flask_wtf/form.py", line 166, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "/home/mzhang/workspace/projects/plenario/plenario/auth.py", line 62, in validate
    .filter(User.email == self.email.data).first()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2367, in first
    ret = list(self[0:1])
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2228, in __getitem__
    return list(res)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2438, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2453, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 729, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 322, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 826, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1159, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
ProgrammingError: (ProgrammingError) relation "plenario_user" does not exist
LINE 2: FROM plenario_user 
             ^
 'SELECT plenario_user.password AS plenario_user_password, plenario_user.id AS plenario_user_id, plenario_user.name AS plenario_user_name, plenario_user.email AS plenario_user_email \nFROM plenario_user \nWHERE plenario_user.email = %(email_1)s \n LIMIT %(param_1)s' {'email_1': u'mengyuzhang@uchicago.edu', 'param_1': 1}
```

**Comment by evz** [comment]
Did you run the [``init_db.py``](https://github.com/UrbanCCD-UChicago/plenario/blob/master/init_db.py) script? Sounds like that may be the problem

**Comment by my-zhang** [comment]
@evz Oh! yeah, exactly. How careless am I ... Thanks a lot.
