### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by TanuMalik** [UrbanCCD-UChicago/plenario#196]
I wanted to do some ShapeETL in my dev instance of Plenario. 
To do ShapeETL, one has to go past WeatherETL. 

Unfortunately, WeatherETL fails for me and the reason is that my Postgres Server is out of memory. 
While the need to do WeatherETL for a dev instance is a separate issue, it might be helpful to have as part of documentation, some basic Postgres configuration and how to change it. Especially a configuration setting that conforms to the test data that Plenario is either downloading or providing. 
The out-of-box Postgres configuration is too low for current ETL of downloaded Weather datasets.  

The failed ETL also leaves the database inconsistent so performing python initdb.py again does not work. Currently SQLAlchemy is smart enough to detect a previous failed transaction, and we should use that knowledge to drop the database and recreate again rather than asking the user to do it. 
 
```
creating master, meta and user tables
creating default user EDE_user
initializing NOAA weather stations
initializing NOAA daily and hourly weather observations for 12/2015
this will take a few minutes ...
finished 66061 rows

Traceback (most recent call last):
  File "init_db.py", line 96, in <module>
    init_db(arguments)
  File "init_db.py", line 16, in init_db
    init_weather()
  File "init_db.py", line 51, in init_weather
    e.initialize_month(datetime.datetime.now().year, datetime.datetime.now().month)
  File "/home/ubuntu/EDE/plenario/plenario/utils/weather.py", line 150, in initialize_month
    self._do_etl(fname, no_daily, no_hourly, weather_stations_list, banned_weather_stations_list, start_line, end_line)
  File "/home/ubuntu/EDE/plenario/plenario/utils/weather.py", line 188, in _do_etl
    self._update(span='hourly')
  File "/home/ubuntu/EDE/plenario/plenario/utils/weather.py", line 313, in _update
    conn.execute(ins)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) out of memory
DETAIL:  Failed on request of size 100663296.
```

**Comment by WillEngler** [comment]
To your immediate concern:

@hectron has added command line switches to init_db.py that let you specify which database init routines you'd like to run. I've merged that from master into the branch we're working on, so you can run `python init_db.py --tables --census` to do the bare minimum to run ShapeETL on some census blocks.

Also, I added some error-handling logic to the init script that should roll back the DB transaction in some cases.

To your bigger concern:

It'd be nice to have a more plug & play way to set up a dev environment that could avoid things like the out of memory issue you're seeing. (I'm curious about your postgres config, because I've gotten @lw334 and @ayang7 running with out of the box settings on their local machines.) Depending on our priorities, I'd like to set aside some time for configuration management and automation after getting the update/delete fix live.

**Comment by WillEngler** [comment]
init_db.py has better error handling and helpful usage messages with the -h flag. Calling this closed.
