### ISSUE TITLE
Unable to install/start

### ISSUE THREAD

**Issue by vivekrs** [UrbanCCD-UChicago/plenario#260]
I followed the documentation through the end and installed all the requirements. It looks like celery is no longer required. Finally, when I run `python runserver.py`, I get the error attached. 
This is on a brand new Ubuntu 16.04.1 x64 VM with Postgres 9.5.4
Please help!

```
ERROR:boto:Caught exception reading instance data
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/boto/utils.py", line 210, in retry_url
    r = opener.open(req, timeout=timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error timed out>
ERROR:boto:Caught exception reading instance data
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/boto/utils.py", line 210, in retry_url
    r = opener.open(req, timeout=timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error timed out>
ERROR:boto:Unable to read instance data, giving up
Could not get INSTANCE_ID
ERROR:boto:401 Unauthorized
ERROR:boto:<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>AuthFailure</Code><Message>Authorization header or parameters are not formatted correctly.</Message></Error></Errors><RequestID>c5c25c1d-0bef-4e4b-a5ba-12bc963e2a8b</RequestID></Response>
Could not get AUTOSCALING_GROUP
Traceback (most recent call last):
  File "runserver.py", line 18, in <module>
    application = create_app()
  File "/home/advis/Projects/plenario/plenario/__init__.py", line 17, in create_app
    from plenario.api import api, cache
  File "/home/advis/Projects/plenario/plenario/api/__init__.py", line 3, in <module>
    from point import timeseries, detail, meta, dataset_fields, grid, detail_aggregate, datadump, get_datadump, get_job_view
  File "/home/advis/Projects/plenario/plenario/api/point.py", line 23, in <module>
    from plenario.api.jobs import make_job_response, submit_job, get_job, set_status, get_status, set_request, get_request, \
  File "/home/advis/Projects/plenario/plenario/api/jobs.py", line 15, in <module>
    from plenario_worker.clients import job_queue
  File "/home/advis/Projects/plenario/plenario_worker/clients.py", line 20, in <module>
    job_queue = sqs_resource.get_queue_by_name(QueueName=JOBS_QUEUE)
  File "/usr/local/lib/python2.7/dist-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 159, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 494, in _make_api_call
    raise ClientError(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidClientTokenId) when calling the GetQueueUrl operation: The security token included in the request is invalid.
```

It looks like it has something to do with connecting to an AWS instance, but I'm unable to figure out exactly what to 'not' run since I'm running this on my local machine.

Any help would be greatly appreciated.

The list/order of installation of dependencies is as follows:

```
git clone https://github.com/UrbanCCD-UChicago/plenario
cd plenario
sudo apt install libpq-dev
sudo apt install libgeos-dev
sudo pip install -r requirements.txt

sudo apt install postgresql
sudo apt install postgresql-client-common
sudo apt install postgresql-client
sudo apt install postgis

sudo -u postgres createuser user
sudo -u postgres createdb -O user plenario_test
sudo -u postgres psql plenario_test
# CREATE EXTENSION postgis;

sudo apt install gdal-bin
sudo apt install redis-server

vi settings.py...

redis-server &
python init_db.py
python runserver.py
```

**Comment by HeyZoos** [comment]
Hey @vivekrs, you're absolutely correct that celery is no longer required. You have caught us at the end of a pretty intense sprint in which a few dependencies were added for AWS services. We have not yet gotten around to smoothing out the local development environment for non-plenario developers, for this I apologize.

In the meantime, if you have valid AWS credentials you'll be able to get it working on your local environment. Looking at the plenario/settings.py file will give you the best idea for what services need to be running.

**Comment by vivekrs** [comment]
Thanks for getting back to me about this @HeyZoos. I'll try to run this on an AWS Instance tonight.
Do you have an approximate plan/ETA for fixing the local development dependencies?

**Comment by HeyZoos** [comment]
@vivekrs No need to run it on an AWS instance, you just need to make an SQS queue and write the queue name in the settings where it says JOBS_QUEUE. That ought to do the trick. Thanks for bringing this to my attention, I'll implement a fix in the coming week and let you know then

**Comment by vivekrs** [comment]
Got it - so you replaced celerey with sqs. I'll try it out tonight.
Again, thanks a lot for your help!
