### ISSUE TITLE
Transportation Permits ETL Error

### ISSUE THREAD

**Issue by HeyZoos** [UrbanCCD-UChicago/plenario#310]
OpenGrid's [#308](https://github.com/Chicago/opengrid/issues/308)

Point ETL ingest of transportation_department_permits dataset has been failing due to the following error:

```
Traceback (most recent call last):
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/celery/app/trace.py", line 367, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/celery/app/trace.py", line 622, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/python/bundle/24/app/plenario/tasks.py", line 77, in update_dataset
    PlenarioETL(meta).update()
  File "/opt/python/bundle/24/app/plenario/etl/point.py", line 50, in update
    self.add()
  File "/opt/python/bundle/24/app/plenario/etl/point.py", line 43, in add
    with self.staging_table as s_table:
  File "/opt/python/bundle/24/app/plenario/etl/point.py", line 95, in __enter__
    self.cols = self._from_inference(text_handle)
  File "/opt/python/bundle/24/app/plenario/etl/point.py", line 188, in _from_inference
    col_type, nullable = iter_column(col_idx, f)
  File "/opt/python/bundle/24/app/plenario/utils/helpers.py", line 62, in iter_column
    for row in reader:
  File "/opt/python/run/venv/lib64/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 4799: ordinal not in range(128)
```

Source dataset: https://data.cityofchicago.org/api/views/pubx-yq2d/rows.csv?accessType=DOWNLOAD

**Comment by HeyZoos** [comment]
#331 Closes this
